CREATE TABLE USERINFO (
    USER_NO NUMBER PRIMARY KEY,             -- 회원번호
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,   -- 아이디
    USER_PWD VARCHAR2(30) NOT NULL,         -- 비밀번호
    USER_NAME VARCHAR2(20) NOT NULL,        -- 이름
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')), -- 성별
    AGE NUMBER,         --나이
    EMAIL VARCHAR2(30),--이메일
    PHONE CHAR(11),     --번호
    ENROLL_DATE DATE DEFAULT SYSDATE   -- 가입일
);

CREATE TABLE USER_SCORE (
    USER_ID VARCHAR2(30) NOT NULL,          -- 유저 아이디
    HIGH_SCORE NUMBER NOT NULL,             -- 최고 스테이지
    CONSTRAINT PK_USER_SCORE PRIMARY KEY (USER_ID),
    CONSTRAINT FK_USER_SCORE FOREIGN KEY (USER_ID)
        REFERENCES USERINFO(USER_ID)
        ON DELETE CASCADE -- 참조해도 삭제 가능
);

CREATE SEQUENCE SEQ_USERNO
START WITH 1 -- 원하는 시작값
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMIT;



