--1.과목유형 테이블(TB_CLASS_TYPE)에 데이터를 추가하시오
INSERT INTO TB_CLASS_TYPE
VALUES ('01','전공필수');
INSERT INTO TB_CLASS_TYPE
VALUES ('02','전공선택');
INSERT INTO TB_CLASS_TYPE
VALUES ('03','교양필수');
INSERT INTO TB_CLASS_TYPE
VALUES ('04','교양선택');
INSERT INTO TB_CLASS_TYPE
VALUES ('05','논문지도');

--2.서브쿼리 이용해서 학생일반정보 테이블 만들기
CREATE TABLE TB_학생일반정보 AS
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_ADDRESS
FROM TB_STUDENT;
 
--3.국어국문학과 학생들의 정보만이 포함되어 있는 하과 정보 테이블만들기
CREATE TABLE TB_국어국문학과 AS
SELECT STUDENT_NO AS 학번,STUDENT_NAME AS 학생이름,'19'||SUBSTR(19,STUDENT_SSN,1,6)AS 출생년도
        ,PROFESSOR_NAME AS 교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO=PROFESSOR_NO)
WHERE DEPARTMENT_NAME='국어국문학과';

/*WHEN SUBSTR(STUDENT_SSN, 7, 1) IN ('1', '2') THEN '19' || SUBSTR(STUDENT_SSN, 1, 2)
        WHEN SUBSTR(STUDENT_SSN, 7, 1) IN ('3', '4') THEN '20' || SUBSTR(STUDENT_SSN, 1, 2)
        ELSE '19' || SUBSTR(STUDENT_SSN, 1, 2)*/
        
    
--4.현 학과들의 정원을 10프로씩 증가
UPDATE TB_DEPARTMENT
SET  CAPACITY=ROUND(CAPACITY+(CAPACITY*0.1))
;

--5.학번 A413042인 박건우 학생의 주소가 "서울시 종로구 숭인동 181-21로 변경되었다고 핳ㄴ다
--주소지를 변경해라
UPDATE TB_STUDENT
SET STUDENT_ADDRESS='서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO='A413042';

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO='A413042';

--6.주민번호 뒷자리를 저장하지 않기로 결정했다. 
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

--7.의학과 김명훈 학생은 2005년 1학기에 자신이 수강한 피부생리학 점수가 잘못었다.
--3.5로 정정하여라
UPDATE TB_GRADE
SET POINT=3.5
WHERE CLASS_NO IN (SELECT CLASS_NO
        FROM TB_GRADE
        JOIN TB_CLASS USING(CLASS_NO)
        JOIN TB_STUDENT USING (STUDENT_NO)
        WHERE (CLASS_NAME='피부생리학' AND STUDENT_NAME='김명훈' 
                AND TERM_NO='200501'));

SELECT CLASS_NO,POINT,CLASS_NAME,TERM_NO
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME='피부생리학';

--8.성적 테이블에서 휴학생드리 성적 항목을 제거
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (
    SELECT STUDENT_NO
    FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y'
);







