--게임 캐릭터 정보
CREATE TABLE GAME (
        JOB_NUM     NUMBER CONSTRAINT JOBNUM_PK PRIMARY KEY,
        JOB_NAME    VARCHAR2(30) CONSTRAINT JOBNAME_NN NOT NULL,
        ATTACT      NUMBER CONSTRAINT ATTACT_NN NOT NULL,
        DEFENSE     NUMBER CONSTRAINT DEFENSE_NN NOT NULL,
        HILL        NUMBER CONSTRAINT HILL_NN NOT NULL,
        ANY1        VARCHAR2(30),
        ANY2        VARCHAR2(30)
);

COMMENT ON COLUMN GAME.JOB_NUM IS '직업 번호';
COMMENT ON COLUMN GAME.JOB_NAME IS '직업 이름';
COMMENT ON COLUMN GAME.ATTACT IS '공격력';
COMMENT ON COLUMN GAME.DEFENSE IS '방어력';
COMMENT ON COLUMN GAME.HILL IS '회복력';
COMMENT ON COLUMN GAME.ANY1 IS '아무거나1';
COMMENT ON COLUMN GAME.ANY2 IS '아무거나2';


--전사
INSERT INTO GAME(
    JOB_NUM,
    JOB_NAME,
    ATTACT,
    DEFENSE,
    HILL,
    ANY1,
    ANY2
)VALUES(
    01,
    '전사',
    100,
    40,
    10,
    NULL,
    NULL);

--수비병
INSERT INTO GAME(
    JOB_NUM,
    JOB_NAME,
    ATTACT,
    DEFENSE,
    HILL,
    ANY1,
    ANY2
)VALUES(
    02,
    '수비병',
    40,
    100,
    10,
    NULL,
    NULL);

--힐러
INSERT INTO GAME(
    JOB_NUM,
    JOB_NAME,
    ATTACT,
    DEFENSE,
    HILL,
    ANY1,
    ANY2
)VALUES(
    03,
    '힐러',
    20,
    20,
    110,
    NULL,
    NULL);


--게임 유저 정보
CREATE TABLE GAME_USER (
        JOB_NUM             NUMBER CONSTRAINT JOBNUM_FK REFERENCES GAME(JOB_NUM),
        USER_NAME           VARCHAR2(30) CONSTRAINT USERNAME_NN NOT NULL,
        HIREDATE            DATE DEFAULT(SYSDATE),
        PLAYER_LEVEL        NUMBER CONSTRAINT LEVEL_NN NOT NULL,
        PLAYER_RANK         VARCHAR2(30) CONSTRAINT RANK_NN NOT NULL,
        ANY3                VARCHAR2(30),
        ANY4                VARCHAR2(30)
);

COMMENT ON COLUMN GAME_USER.JOB_NUM          IS '직업 번호';
COMMENT ON COLUMN GAME_USER.USER_NAME        IS '유저이름';
COMMENT ON COLUMN GAME_USER.HIREDATE         IS '시작날짜';
COMMENT ON COLUMN GAME_USER.PLAYER_LEVEL     IS '게임레벨';
COMMENT ON COLUMN GAME_USER.PLAYER_RANK      IS '게임 순위';
COMMENT ON COLUMN GAME_USER.ANY3             IS '아무거나3';
COMMENT ON COLUMN GAME_USER.ANY4             IS '아무거나4';

--유저정보1
INSERT INTO GAME_USER(
    JOB_NUM,
    USER_NAME,
    HIREDATE,
    PLAYER_LEVEL ,
    PLAYER_RANK,
    ANY3,
    ANY4
)VALUES(
    01,
    '이순신',
    SYSDATE,
    40,
    '3위',
    NULL,
    NULL);
--유저정보2
INSERT INTO GAME_USER(
    JOB_NUM,
    USER_NAME,
    HIREDATE,
    PLAYER_LEVEL ,
    PLAYER_RANK,
    ANY3,
    ANY4
)VALUES(
    02,
    '김춘추',
    '20/12/08',
    55,
    '2위',
    NULL,
    NULL);
--유저정보3
INSERT INTO GAME_USER(
    JOB_NUM,
    USER_NAME,
    HIREDATE,
    PLAYER_LEVEL ,
    PLAYER_RANK,
    ANY3,
    ANY4
)VALUES(
    03,
    '홍길동',
    '19/01/01',
    65,
    '1위',
    NULL,
    NULL);
--유저정보4
INSERT INTO GAME_USER(
    JOB_NUM,
    USER_NAME,
    HIREDATE,
    PLAYER_LEVEL ,
    PLAYER_RANK,
    ANY3,
    ANY4
)VALUES(
    01,
    '김미래',
    '2023/04/05',
    30,
    '4위',
    NULL,
    NULL);
--유저정보5
INSERT INTO GAME_USER(
    JOB_NUM,
    USER_NAME,
    HIREDATE,
    PLAYER_LEVEL ,
    PLAYER_RANK,
    ANY3,
    ANY4
)VALUES(
    03,
    '신유승',
    SYSDATE,
    1,
    '5위',
    NULL,
    NULL);

--순위 순으로 정보 나열
SELECT *
FROM GAME_JOB;
JOIN GAME_USER USING (JOB_NUM)
ORDER BY SUBSTR(PLAYER_RANK,1,1) ASC;

--유저 플레이타임 컬럼 추가,컬럼명추가
ALTER TABLE GAME_USER ADD PLAY_TIME VARCHAR(10);
COMMENT ON COLUMN GAME_USER.PLAY_TIME IS '플레이 시간';

ALTER TABLE GAME RENAME COLUMN ANY1 TO ANY5;
ALTER TABLE GAME RENAME COLUMN ANY5 TO ANY1;

--유저순위 UNIQUE추가
ALTER TABLE GAME_USER ADD CONSTRAINT RANK_UQ UNIQUE(PLAYER_RANK);

--GMAE테이블명 GAME_JOB으로 바꾸기
ALTER TABLE GAME RENAME TO GAME_JOB;

--전사 ANY1에 설명 간단히 적기
UPDATE GAME_JOB
SET ANY1 = '공격력이 가장 높다!'
WHERE JOB_NUM = 1;

--김춘주에 설명 간단히 적기
UPDATE GAME_USER
SET ANY3 = '저번시즌 1등이였다.'
WHERE USER_NAME = '김춘추';

--모든 직업에 공격력을 10프로 올려라.
UPDATE GAME_JOB
SET ATTACT = ATTACT +ATTACT *0.1;

--DB에 저장
COMMIT;
--신유승 삭제
DELETE FROM GAME_USER
WHERE USER_NAME ='신유승';
--신유승 삭제 전으로 복구
ROLLBACK;

--탈퇴유저 확인하기
ALTER TABLE GAME_USER ADD W ITHDRAWAL CHAR(1) DEFAULT'N' CONSTRAINT WITHDRAWAL_CK CHECK (WITHDRAWAL IN('Y','N')); 
COMMENT ON COLUMN GAME_USER.WITHDRAWAL IS '탈퇴한 유저인가?';
UPDATE GAME_USER
SET WITHDRAWAL = 'Y'
WHERE USER_NAME = '신유승';

DROP TABLE GAME_USER;
DROP TABLE GAME_JOB;






















